<!--load_essentials.js-->
		document.getElementById("header").innerHTML =
		"<nav class='menu off'>"
		+	"<div class='container'>"
		+		"<ul class='nav'>"
		+			"<li><a href='"+paths+"index.html'>Home</a>"
		+			"</li>"
		+			"<li><a href='"+paths+"about-us.html'>About Us</a>"
		+			"</li>"
		+			"<li><a href='"+paths+"campus.html'>Campus Life</a>"
		+			"</li>"
		+			"<li><a href='"+paths+"#'>Programmes</a>"
		+				"<ul class='child-menu'>"
		+					"<li><a href='"+paths+"macomm.html'>MA in Communication</a>"
		+					"</li>"
		+					"<li><a href='"+paths+"maijs.html'>MA in International Journalism Studies</a>"
		+					"</li>"
		+					"<li><a href='"+paths+"maftnm.html'>MA in Producing for Film, Television & New Media</a>"
		+					"</li>"
		+					"<li><a href='"+paths+"mmgt.html'>MSocSc in Media Management</a>"
		+					"</li>"
		+				"</ul>"
		+			"</li>"
		+			"<li><a href='"+paths+"student-life.html'>Student Life</a>"
		+			"</li>"
		+			"<li><a href='"+paths+"highlights.html'>Highlights</a>"
		+			"</li>"
		+			"<li><a href='"+paths+"news/2018.html'>News & Events</a>"
		+			"</li>"
		+			"<li><a href='https://iss.hkbu.edu.hk/amsappl_pg/welcome.jsf' target='blank'>Admissions</a>"
		+			"</li>"
		+			"<li><a href='"+paths+"contact-us.html'>Contact Us</a>"
		+			"</li>"
		+		"</ul>"
		+		"<ul class='navSoc'>"
		+			"<a href='https://www.facebook.com/hkbucommtpg' target='_blank' title='Follow Us on Facebook'><li class='icon_social icon_social_fb'>"
		+			"</li></a>"
		+			"<a href='http://www.weibo.com/hkbucommtpg' target='_blank' title='Follow Us on Weibo'><li class='icon_social icon_social_sina'>"
		+			"</li></a>"
		+			"<a href='http://www.comm.hkbu.edu.hk/comd-www/english/about_comm/m_wechat.htm' target='_blank' title='Follow Us on WeChat'><li class='icon_social icon_social_wechat'>"
		+			"</li></a>"
		+		"</ul>"
		+	"</div>"
		+"</nav>"
		+"<nav class='navbar navbar-fixed-top navbar-custom'>"
		+"	<div class='container'>"
		+"		<div class='navbar-header'>"
		+"			<a href='http://hkbu.edu.hk' target='_blank' title='HKBU'>"
		+"				<div id='logo-bu'></div>"
		+"			</a>"
		+"			<a href='http://www.comm.hkbu.edu.hk/' target='_blank' title='School of Communication'>"
		+"				<div id='logo-sc'></div>"
		+"			</a>"
		+"		</div>"
		+"		<div class='navbar-collapse collapse'>"
		+"			<ul class='nav navbar-nav navbar-right'>"
		+"				<li class='icon_social icon_social_fb'>"
		+"					<a href='https://www.facebook.com/hkbucommtpg' target='_blank' title='Follow Us on Facebook'></a>"
		+"				</li>"
		+"				<li class='icon_social icon_social_sina'>"
		+"					<a href='http://www.weibo.com/hkbucommtpg' target='_blank' title='Follow Us on Weibo'></a>"
		+"				</li>"
		+"				<li class='icon_social icon_social_wechat'>"
		+"					<a href='http://www.comm.hkbu.edu.hk/comd-www/english/about_comm/m_wechat.htm' target='_blank' title='Follow Us on WeChat'></a>"
		+"				</li>"
		+"				<li class='icon_langAll'><a href='javascript:;'>EN</a>"
		+"				</li>"
		+"				<li class='icon_langAll'><a href='javascript:SwitchLang2HK()'>繁</a>"
		+"				</li>"
		+"				<li class='icon_langAll'><a href='javascript:SwitchLang2CN()'>簡</a>"
		+"				</li>"
		+"				<li class='icon_lang'><a href='javascript:;'>EN</a>"
		+"					<ul>"
		+"						<li class='icon_lang'><a href='javascript:SwitchLang2HK()'>繁</a>"
		+"						</li>"
		+"						<li class='icon_lang'><a href='javascript:SwitchLang2CN()'>簡</a>"
		+"						</li>"
		+"					</ul>"
		+"				</li>"
		+"				<li class='icon_menu'>"
		+"					<a href='javascript:void(0)' class='menu-toggle'></a>"
		+"				</li>"
		+"			</ul>"
		+"		</div>"
		+"	</div>"
		+"</nav>";
		
		
		
		
	document.getElementById("footer").innerHTML =
	"	<div class='row footer hidden-xs hidden-sm'>"
	+"		<div class='container footer-menu'>"
	+"			<div id='footer-menu-row-1'>"
	+"				<div class='col-lg-3 col-md-3'>"
	+"					<ul class='title'><a href='"+paths+"about-us.html'>About us</a></ul>"
	+"					<li><a href='"+paths+"about-us.html#top-slides'>School of Communication</a></li>"
	+"					<li><a href='"+paths+"about-us.html#aboutus-vision'>Vision & Mission</a></li>"
	+"					<li><a href='"+paths+"about-us.html#aboutus-timeline'>The History</a></li>"
	+"					<li><a href='"+paths+"about-us.html#aboutus-progs'>Programmes</a></li>"
	+"				</div>"
	+"				<div class='col-lg-3 col-md-3'>"
	+"					<ul class='title'>Programmes</ul>"
	+"					<li><a href='"+paths+"macomm.html'>MA in Communication</a></li>"
	+"					<li><a href='"+paths+"maijs.html'>MA In International"
	+"						<br>Journalism Studies</a></li>"
	+"					<li><a href='"+paths+"maftnm.html'>MA in Producing for Film,"
	+"						<br>Television & New Media</a></li>"
	+"					<li><a href='"+paths+"mmgt.html'>MSocSc in Media Management</a></li>"
	+"				</div>"
	+"				<div class='col-lg-3 col-md-3'>"
	+"					<ul class='title'><a href='"+paths+"highlights.html'>Highlights</a></ul>"
	+"					<li><a href='"+paths+"highlights.html#highlights-trips'>International Study Trips</a></li>"
	+"					<li><a href='"+paths+"highlights.html#highlights-ppww'>Pulitzer Prize Winners Workshop</a></li>"
	+"					<li><a href='"+paths+"highlights.html#highlights-sopa'>HKBU-SOPA Award Winners Forum</a></li>"
	+"					<li><a href='"+paths+"highlights.html#highlights-salon'>International Media Salon</a></li>"
	+"					<li><a href='"+paths+"highlights.html#highlights-seminars'>Seminars & Workshops</a></li>"
	+"					<li><a href='"+paths+"highlights.html#highlights-tutorial'>Tutorial System</a></li>"
	+"				</div>"
	+"				<div class='col-lg-3 col-md-3'>"
	+"					<ul class='title'><a href='https://iss.hkbu.edu.hk/amsappl_pg/welcome.jsf' target='blank'>Admissions</a></ul>"
	+"					<ul class='title' style='margin-top: 38px'><a href='"+paths+"contact-us.html'>Contact Us</a></ul>"
	+"					<li><a href='"+paths+"contact-us.html#std-enquiries'>Admissions Enquiries</a></li>"
	+"					<li><a href='"+paths+"contact-us.html#std-enquiries'>Programme Curriculum Enquiries</a></li>"
	+"				</div>"
	+"			</div>"
	+"			<!-- Footer Menu Row 1-->"
	+"			<div id='footer-menu-row-2'>"
	+"				<div class='col-lg-3 col-md-3'>"
	+"					<ul class='title'><a href='"+paths+"campus.html'>Campus Life</a></ul>"
	+"					<li><a href='"+paths+"campus.html#labs'>Computer Labs</a></li>"
	+"					<li><a href='"+paths+"campus.html#studios'>Studios</a></li>"
	+"					<li><a href='"+paths+"campus.html#equip'>Equipment</a></li>"
	+"					<li><a href='"+paths+"campus.html#conference'>Conference Room</a></li>"
	+"					<li><a href='"+paths+"campus.html#theatre'>Lecture Theatre</a></li>"
	+"				</div>"
	+"				<div class='col-lg-3 col-md-3'>"
	+"					<ul class='title'><a href='"+paths+"student-life.html'>Student Life</a></ul>"
	+"					<li><a href='"+paths+"student-life.html#student02'>Prospective Students</a></li>"
	+"					<li><a href='"+paths+"student-life.html#student03'>Current Students</a></li>"
	+"					<li><a href='"+paths+"student-life.html#student04'>Alumni</a></li>"
	+"				</div>"
	+"				<div class='col-lg-3 col-md-3'>"
	+"					<ul class='title'><a href='"+paths+"news/2018.html'>News & Events</a></ul>"
	+"					<li><a href='"+paths+"news/2018.html'>News & Events</a></li>"
	+"					<li>Archive</li>"
	+"					<li>School of Communication Newsletter</li>"
	+"				</div>"
	+"				<div class='col-lg-3 col-md-3'>"
	+"					<ul class='title'>Follow us</ul>"
	+"					<div id='social-media'>"
	+"						<a href='https://www.facebook.com/hkbucommtpg' target='_blank' title='Follow Us on Facebook'><div class='icon_social icon_social_fb'>"	
	+"						</div></a>"
	+"						<a href='http://www.weibo.com/hkbucommtpg' target='_blank' title='Follow Us on Weibo'><div class='icon_social icon_social_sina'>"
	+"						</div></a>"
	+"						<a href='http://www.comm.hkbu.edu.hk/comd-www/english/about_comm/m_wechat.htm' target='_blank' title='Follow Us on WeChat'><div class='icon_social icon_social_wechat'>"
	+"						</div> </a>"
	+"					</div>"
	+"					<!-- Social Media -->"
	+"				</div>"
	+"				<!-- Footer Menu Row 2-->"
	+"				</div>"
	+"				<!-- Footer Menu Row 3-->"
	+"				<div class='col-lg-9 copyright'>"
	+"					© 2017 Hong Kong Baptist University. All Rights Reserved."
	+"				</div>"
	+"				<div class='col-lg-3 footer-logo'>"
	+"					<a href='http://hkbu.edu.hk' target='_blank' title='HKBU'>"
	+"						<div id='logo-bu'></div>"
	+"					</a>"
	+"				</div>"
	+"			</div>"
	+"		</div>"	
	+"		<!-- Mobile Footer -->"	
	+"		<div class='row footer-mobile hidden-md hidden-lg'>"	
	+"			<div class='container footer-menu-m'>"	
	+"				<div id='footer-menu-row-m'>"	
	+"					<div class='col-lg-3 col-md-3'>"	
	+"						<div class='panel-group'>"	
	+"							<div class='panel panel-default'>"	
	+"								<div class='panel-heading'>"	
	+"									<a href='"+paths+"about-us.html'><h4 class='panel-title'>About Us</h4></a>"	
	+"								</div>"	
	+"							</div>"	
	+"						</div>"	
	+"					</div>"	
	+"					<div class='col-lg-3 col-md-3'>"	
	+"						<div class='panel-group'>"	
	+"							<div class='panel panel-default'>"	
	+"								<div class='panel-heading'>"	
	+"									<a href='"+paths+"campus.html'><h4 class='panel-title'>Campus Life</h4></a>"	
	+"								</div>"	
	+"							</div>"	
	+"						</div>"	
	+"					</div>"	
	+"					<div class='col-lg-3 col-md-3'>"	
	+"						<div class='panel-group'>"	
	+"							<div class='panel panel-default'>"	
	+"								<div class='panel-heading'>"	
	+"									<a href='"+paths+"student-life.html'><h4 class='panel-title'>Student Life</h4></a>"	
	+"								</div>"	
	+"							</div>"	
	+"						</div>"	
	+"					</div>"	
	+"					<div class='col-lg-3 col-md-3'>"	
	+"						<div class='panel-group'>"	
	+"							<div class='panel panel-default'>"	
	+"								<div class='panel-heading'>"	
	+"									<a href='#collapse_programme' data-toggle='collapse' data-target='#collapse_programme' aria-expanded='false'>"	
	+"										<h4 class='panel-title'>Programme"	
	+"										  <span class='glyphicon glyphicon-chevron-down' style='float: right'></span>"	
	+"										</h4>"	
	+"									</a>"	
	+"								</div>"	
	+"								<div id='collapse_programme' class='panel-collapse collapse'>"	
	+"									<ul class='list-group'>"	
	+"										<a href='"+paths+"maijs.html'>"	
	+"											<li class='list-group-item'>MA In International in Journalism Studies</li>"	
	+"										</a>"	
	+"										<a href='"+paths+"macomm.html'>"	
	+"											<li class='list-group-item'>MA in Communication</li>"	
	+"										</a>"	
	+"										<a href='"+paths+"maftnm.html'>"	
	+"											<li class='list-group-item'>MA in Producing for Film, Television & New Media</li>"	
	+"										</a>"	
	+"										<a href='"+paths+"mmgt.html'>"	
	+"											<li class='list-group-item'>MSocSc in Media Management</li>"	
	+"										</a>"	
	+"									</ul>"	
	+"								</div>"	
	+"							</div>"	
	+"						</div>"	
	+"					</div>"	
	+"					<div class='col-lg-3 col-md-3'>"	
	+"						<div class='panel-group'>"	
	+"							<div class='panel panel-default'>"	
	+"								<div class='panel-heading'>"	
	+"									<a href='"+paths+"highlights.html'><h4 class='panel-title'>Highlights</h4></a>"	
	+"								</div>"	
	+"							</div>"	
	+"						</div>"	
	+"					</div>"	
	+"					<div class='col-lg-3 col-md-3'>"	
	+"						<div class='panel-group'>"	
	+"							<div class='panel panel-default'>"	
	+"								<div class='panel-heading'>"	
	+"									<a href='#collapse_news' data-toggle='collapse' data-target='#collapse_news' aria-expanded='false'>"	
	+"										<h4 class='panel-title'>News & Events<span class='glyphicon glyphicon-chevron-down' style='float: right'></span>"	
	+"										</h4>"	
	+"									</a>"	
	+"								</div>"	
	+"								<div id='collapse_news' class='panel-collapse collapse'>"	
	+"									<ul class='list-group'>"	
	+"										<a href='"+paths+"news/2018.html'><li class='list-group-item'>News & Events</li></a>"	
	+"										<li class='list-group-item'>Archive</li>"	
	+"										<li class='list-group-item'>School of Communication Newsletter</li>"	
	+"									</ul>"	
	+"								</div>"	
	+"							</div>"	
	+"						</div>"	
	+"					</div>"	
	+"					<div class='col-lg-3 col-md-3'>"	
	+"						<div class='panel-group'>"	
	+"							<div class='panel panel-default'>"	
	+"								<div class='panel-heading'>"	
	+"									<a href='https://iss.hkbu.edu.hk/amsappl_pg/welcome.jsf' target='blank'>"	
	+"										<h4 class='panel-title'>Admissions</h4>"	
	+"									</a>"	
	+"								</div>"	
	+"							</div>"	
	+"						</div>"	
	+"					</div>"	
	+"					<div class='col-lg-3 col-md-3'>"	
	+"						<div class='panel-group'>"	
	+"							<div class='panel panel-default'>"	
	+"								<div class='panel-heading'>"	
	+"									<a href='"+paths+"contact-us.html'><h4 class='panel-title'>Contact Us</h4></a>"	
	+"								</div>"	
	+"							</div>"	
	+"						</div>"	
	+"					</div>"	
	+"					<div class='col-lg-12 copyright'>"	
	+"						© 2017 Hong Kong Baptist University."	
	+"						<br>All Rights Reserved."	
	+"					</div>"	
	+"				</div>"	
	+"			</div>"	
	+"		</div>"	
	+"		<!-- Mobile Footer -->"	;
